import {cp,mkdir,rm} from 'node:fs/promises';
await rm('dist',{recursive:true,force:true});
await mkdir('dist/src/lib',{recursive:true});
await mkdir('dist/src/data',{recursive:true});
await cp('index.html','dist/index.html');
await cp('src/app.js','dist/src/app.js');
await cp('src/styles.css','dist/src/styles.css');
await cp('src/lib/engine.js','dist/src/lib/engine.js');
await cp('src/data/content.js','dist/src/data/content.js');
console.log('Built dependency-free static site in dist/');
