import {policies,residents,trials,sources} from './data/content.js';
import {applyTrial,createPopulation,equitySummary,levelFor,METRICS,operatingCost} from './lib/engine.js';

const app=document.querySelector('#app'), metricNames={physical:'Physical health',stability:'Health stability',access:'Access to care',financial:'Financial security',dignity:'Trust & dignity'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const seed=()=>Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%32]).join('');
let state={phase:'welcome',mode:'demo',seed:seed(),selections:Object.fromEntries(policies.map(p=>[p.id,0])),population:createPopulation(residents),round:0};
const save=()=>localStorage.setItem('btv-session',JSON.stringify(state));
const button=(label,action,cls='')=>`<button class="${cls}" data-action="${action}">${label}</button>`;
function render(){window.scrollTo(0,0);if(state.phase==='welcome')return welcome();if(state.phase==='policy')return policy();if(state.phase==='residents')return population();if(state.phase==='trial')return trial();return results()}
function welcome(){app.innerHTML=`<main id="main" class="welcome"><section class="hero"><p class="eyebrow">A healthcare equity simulation</p><h1>Behind the Veil</h1><p class="subtitle">Build a just healthcare system before you know where you will land within it.</p><div class="actions">${button('Create local teacher session','start')}${button('Solo preview','start','secondary')}${button('10-minute practice','practice','ghost')}</div></section><section class="notice"><h2>Before you begin</h2><p>This educational model does not predict any person's health. It includes non-graphic illness, hospitalization, financial strain, discrimination, and pregnancy complications with recovery. It excludes death, mental-health, and substance-use scenarios.</p></section></main>`}
function policy(){const spent=policies.reduce((s,p)=>s+p.levels[state.selections[p.id]].cost,0),groups=policies.reduce((a,p)=>((a[p.category]??=[]).push(p),a),{});app.innerHTML=`<main id="main" class="shell"><header class="top"><div><p class="eyebrow">Original position</p><h1>Build behind the veil</h1></div><div class="budget" aria-live="polite"><strong>${30-spent}</strong><span>of 30 points left</span></div></header><div class="callout"><strong>Scarcity is a simulation constraint.</strong> Consider whose risks remain uncovered.</div>${Object.entries(groups).map(([c,ps])=>`<section><h2>${esc(c)}</h2><div class="policy-grid">${ps.map(p=>`<article class="policy"><h3>${esc(p.name)}</h3><p>${esc(p.benefit)}</p><fieldset><legend>Investment level</legend>${p.levels.map((l,i)=>`<label><input type="radio" name="${p.id}" data-policy="${p.id}" value="${i}" ${state.selections[p.id]===i?'checked':''}><span>${esc(l.name)}<small>${i?`${l.cost} setup · ${l.operating}/round`:''}</small></span></label>`).join('')}</fieldset></article>`).join('')}</div></section>`).join('')}<footer class="sticky"><span>Operating cost: <strong>${operatingCost(policies,state.selections)} points/round</strong></span>${button('Lift the veil','lift')}</footer></main>`}
function population(){app.innerHTML=`<main id="main" class="shell"><header class="top"><div><p class="eyebrow">The veil is lifted</p><h1>Meet your residents</h1></div>${button('Begin trials','begin')}</header><div class="callout"><strong>Every group has the same population.</strong> Each advocate follows several residents while the group remains responsible for everyone.</div><div class="resident-grid">${state.population.map((r,i)=>`<article class="resident"><div class="avatar" aria-hidden="true">${r.name[0]}</div><div><p class="eyebrow">Advocate ${'ABCDE'[i%5]}</p><h2>${esc(r.name)}, ${esc(r.age)}</h2><p>${esc(r.story)}</p></div></article>`).join('')}</div></main>`}
function trial(){const t=trials[state.round];app.innerHTML=`<main id="main" class="shell"><header><p class="eyebrow">Health trial</p><h1>${esc(t.title)}</h1><p class="subtitle small">${esc(t.prompt)}</p></header><div class="resident-grid decisions">${state.population.map(r=>`<article class="resident"><div><h2>${esc(r.name)}</h2><p>${esc(r.story)}</p><fieldset><legend>Advocate's routine decision</legend>${t.options.map(o=>`<label><input type="radio" name="choice-${r.id}" value="${o.id}" ${o.id===t.defaultChoice?'checked':''}><span>${esc(o.label)}</span></label>`).join('')}</fieldset></div></article>`).join('')}</div><footer class="sticky"><span>Choices can change until the round advances.</span>${button('Resolve round','resolve')}</footer></main>`}
function csv(){const rows=[['resident',...METRICS,'overall'],...state.population.map(r=>[r.name,...METRICS.map(m=>r.metrics[m]),Math.round(METRICS.reduce((n,m)=>n+r.metrics[m],0)/5)])];download(new Blob([rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'}),`Behind_the_Veil_${state.seed}.csv`)}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function results(){const s=equitySummary(state.population);app.innerHTML=`<main id="main" class="shell"><header class="top"><div><p class="eyebrow">Equity review</p><h1>What did your system make possible?</h1></div>${button('Start over','reset','secondary')}</header><section class="score-panel"><div><span>Rawlsian focus</span><strong>${s.leastAdvantaged.map(r=>r.name).join(', ')}</strong><small>Residents facing the greatest combined barriers</small></div><div><span>Outcome gap</span><strong>${s.gap}</strong><small>Inspect individual results—not only the gap.</small></div></section><h2>Population outcomes</h2><div class="resident-grid">${state.population.map(r=>`<article class="resident result"><div><h3>${esc(r.name)}</h3><div class="metrics">${METRICS.map(m=>`<div class="metric m-${levelFor(r.metrics[m]).toLowerCase().replace(' ','-')}"><span>${metricNames[m]}</span><strong>${levelFor(r.metrics[m])}</strong></div>`).join('')}</div><details><summary>Why did this happen?</summary>${r.history.flatMap(h=>h.causes).map(c=>`<p>${esc(c)}</p>`).join('')||'<p>No special barrier was triggered in this round.</p>'}</details></div></article>`).join('')}</div><section class="debrief"><h2>Defend, reveal, reconsider</h2><ol><li>Who carried the greatest burdens—and why?</li><li>Which identities and circumstances intersected?</li><li>How did policies distribute benefits, risks, and opportunities?</li><li>Every group received identical conditions. What differences came from systems and choices?</li><li>How does protecting the least advantaged change your judgment?</li></ol></section><div class="export">${button('Download results CSV','csv')}${button('Print / save PDF','print')}${button('Source list','sources')}</div><p class="disclaimer">Seed ${state.seed}. Educational abstraction informed by evidence—not a prediction.</p></main>`}
app.addEventListener('change',e=>{if(e.target.dataset.policy){const id=e.target.dataset.policy,n=Number(e.target.value),p=policies.find(x=>x.id===id),spent=policies.reduce((s,x)=>s+x.levels[state.selections[x.id]].cost,0)-p.levels[state.selections[id]].cost+p.levels[n].cost;if(spent<=30){state.selections[id]=n;save();policy()}else{alert('That investment exceeds the 30-point budget.')}}});
app.addEventListener('click',e=>{const a=e.target.dataset.action;if(!a)return;if(a==='start'||a==='practice'){state.mode=a;state.phase='policy'}if(a==='lift')state.phase='residents';if(a==='begin')state.phase='trial';if(a==='resolve'){const t=trials[state.round],choices=Object.fromEntries(state.population.map(r=>[r.id,document.querySelector(`input[name="choice-${r.id}"]:checked`).value]));state.population=applyTrial(state.population,t,choices,state.selections,state.seed);state.round++;state.phase=state.round>=trials.length?'results':'trial'}if(a==='csv')return csv();if(a==='print')return print();if(a==='sources')return alert(sources.map(s=>`${s.org}: ${s.title}\n${s.url}`).join('\n\n'));if(a==='reset'){localStorage.removeItem('btv-session');location.reload();return}save();render()});
try{const previous=JSON.parse(localStorage.getItem('btv-session'));if(previous?.phase)state=previous}catch{}render();
