import React, { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import JSZip from 'jszip';
import { policies, residents, trials, sources } from './data/content.js';
import { createPopulation, applyTrial, equitySummary, levelFor, METRICS, operatingCost } from './lib/engine.js';

const metricNames={physical:'Physical health',stability:'Health stability',access:'Access to care',financial:'Financial security',dignity:'Trust & dignity'};
const initialSelections=Object.fromEntries(policies.map(p=>[p.id,0]));
const download=(blob,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
const randomCode=()=>Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%32]).join('');

function Metric({name,value}){const level=levelFor(value);return <div className={`metric m-${level.toLowerCase().replace(' ','-')}`}><span>{metricNames[name]}</span><strong>{level}</strong></div>}

function Welcome({onStart}){
 return <main id="main" className="welcome"><section className="hero"><p className="eyebrow">A healthcare equity simulation</p><h1>Behind the Veil</h1><p className="subtitle">Build a just healthcare system before you know where you will land within it.</p><div className="actions"><button onClick={()=>onStart('teacher')}>Create teacher session</button><button className="secondary" onClick={()=>onStart('demo')}>Solo preview</button><button className="ghost" onClick={()=>onStart('practice')}>10-minute practice</button></div></section><section className="notice"><h2>Before you begin</h2><p>This is an educational model informed by evidence. It does not predict any individual person's health. It includes non-graphic examples of illness, hospitalization, financial strain, discrimination, pregnancy complications with recovery, and barriers to care. It excludes death, mental-health, and substance-use scenarios.</p></section></main>
}

function PolicyLab({selections,setSelections,onContinue,practice}){
 const spent=policies.reduce((s,p)=>s+p.levels[selections[p.id]].cost,0), remaining=30-spent;
 const grouped=Object.groupBy ? Object.groupBy(policies,p=>p.category) : policies.reduce((a,p)=>((a[p.category]??=[]).push(p),a),{});
 function choose(policy,level){const nextCost=spent-policy.levels[selections[policy.id]].cost+policy.levels[level].cost;if(nextCost<=30)setSelections({...selections,[policy.id]:level});}
 return <main id="main" className="shell"><header className="top"><div><p className="eyebrow">Original position</p><h1>Build behind the veil</h1></div><div className="budget" aria-live="polite"><strong>{remaining}</strong><span>of 30 points left</span></div></header><div className="callout"><strong>Scarcity is a simulation constraint.</strong> It does not mean resources must always be scarce. You cannot fund everything here, so consider whose risks your choices leave uncovered.</div>{Object.entries(grouped).map(([category,items])=><section key={category}><h2>{category}</h2><div className="policy-grid">{items.map(p=><article className="policy" key={p.id}><h3>{p.name}</h3><p>{p.benefit}</p><fieldset><legend>Investment level</legend>{p.levels.map((l,i)=><label key={l.name}><input type="radio" name={p.id} checked={selections[p.id]===i} onChange={()=>choose(p,i)}/><span>{l.name}<small>{i?`${l.cost} setup · ${l.operating}/round`:''}</small></span></label>)}</fieldset></article>)}</div></section>)}<footer className="sticky"><span>Operating cost: <strong>{operatingCost(policies,selections)} points per round</strong></span><button onClick={onContinue}>{practice?'Run practice':'Lift the veil'}</button></footer></main>
}

function Residents({population,assignments,onContinue}){
 return <main id="main" className="shell"><header className="top"><div><p className="eyebrow">The veil is lifted</p><h1>Meet your residents</h1></div><button onClick={onContinue}>Begin the trials</button></header><div className="callout"><strong>Every group has the same population.</strong> This fact is normally revealed during the final comparison. Each advocate follows several residents, while the group remains responsible for everyone.</div><div className="resident-grid">{population.map((r,i)=><article className="resident" key={r.id}><div className="avatar" aria-hidden="true">{r.name[0]}</div><div><p className="eyebrow">Advocate {assignments[i%assignments.length]}</p><h2>{r.name}, {r.age}</h2><p>{r.story}</p></div></article>)}</div></main>
}

function Trial({trial,population,selections,seed,onComplete}){
 const [choices,setChoices]=useState(Object.fromEntries(population.map(r=>[r.id,trial.defaultChoice])));
 return <main id="main" className="shell"><header><p className="eyebrow">Health trial</p><h1>{trial.title}</h1><p className="subtitle small">{trial.prompt}</p></header><div className="resident-grid decisions">{population.map(r=><article className="resident" key={r.id}><div><h2>{r.name}</h2><p>{r.story}</p><fieldset><legend>Advocate's routine decision</legend>{trial.options.map(o=><label key={o.id}><input type="radio" name={`${trial.id}-${r.id}`} checked={choices[r.id]===o.id} onChange={()=>setChoices({...choices,[r.id]:o.id})}/><span>{o.label}</span></label>)}</fieldset></div></article>)}</div><footer className="sticky"><span>Choices can be changed until the round advances.</span><button onClick={()=>onComplete(applyTrial(population,trial,choices,selections,seed))}>Resolve round</button></footer></main>
}

function Results({population,selections,seed,onRestart}){
 const summary=equitySummary(population);
 const group={name:'Local Preview Group',selections,population,summary};
 function workbook(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{seed,gap:summary.gap,...summary.averages}]),'Overview');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(policies.map(p=>({policy:p.name,level:p.levels[selections[p.id]].name,setup_cost:p.levels[selections[p.id]].cost,operating_cost:p.levels[selections[p.id]].operating}))),'Policies');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(population.flatMap(r=>r.history.map(h=>({resident:r.name,trial:h.trial,choice:h.choice,causes:h.causes.join(' | '),...h.metrics}))),'Trial Results');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(population.map(r=>({resident:r.name,...r.metrics,overall:Math.round(METRICS.reduce((n,m)=>n+r.metrics[m],0)/5)}))),'Equity Measures');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(summary.leastAdvantaged.map(r=>({resident:r.name,discussion:`Which policies or barriers most shaped ${r.name}'s outcome?`}))),'Critical Moments');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(sources),'Sources');XLSX.writeFile(wb,`Behind_the_Veil_${seed}.xlsx`)}
 function makePdf(title='Group report'){const doc=new jsPDF();doc.setFontSize(20);doc.text('Behind the Veil',18,20);doc.setFontSize(13);doc.text(title,18,30);doc.setFontSize(10);doc.text(`Reproducibility seed: ${seed}`,18,38);doc.text(`Outcome gap: ${summary.gap} points (internal analytic scale)`,18,45);doc.text('Least advantaged residents',18,56);summary.leastAdvantaged.forEach((r,i)=>doc.text(`${r.name}: ${METRICS.map(m=>`${metricNames[m]}—${levelFor(r.metrics[m])}`).join('; ')}`,18,64+i*8,{maxWidth:175}));doc.text('Discussion prompts',18,105);['Who carried the greatest burdens in your system—and why?','Which policy interaction mattered most?','Did equal treatment create equitable outcomes?','What would you change with five additional points?'].forEach((q,i)=>doc.text(`${i+1}. ${q}`,18,113+i*8,{maxWidth:175}));return doc}
 async function zip(){const z=new JSZip();z.file('group-report.pdf',makePdf().output('arraybuffer'));z.file('class-comparison.pdf',makePdf('Class comparison — local preview').output('arraybuffer'));download(await z.generateAsync({type:'blob'}),`Behind_the_Veil_reports_${seed}.zip`)}
 return <main id="main" className="shell"><header className="top"><div><p className="eyebrow">Equity review</p><h1>What did your system make possible?</h1></div><button className="secondary" onClick={onRestart}>Start over</button></header><section className="score-panel"><div><span>Rawlsian focus</span><strong>{summary.leastAdvantaged.map(r=>r.name).join(', ')}</strong><small>Residents facing the greatest combined barriers</small></div><div><span>Outcome gap</span><strong>{summary.gap}</strong><small>Lower gaps suggest more even outcomes; inspect individual results too.</small></div></section><h2>Population outcomes</h2><div className="resident-grid">{population.map(r=><article className="resident result" key={r.id}><div><h3>{r.name}</h3><div className="metrics">{METRICS.map(m=><Metric key={m} name={m} value={r.metrics[m]}/>)}</div><details><summary>Why did this happen?</summary>{r.history.flatMap((h,i)=>h.causes.map((c,j)=><p key={`${i}-${j}`}>{c}</p>))}</details></div></article>)}</div><section className="debrief"><h2>Defend, reveal, reconsider</h2><ol><li>Who carried the greatest burdens in your system?</li><li>Which interacting identities and circumstances mattered?</li><li>How did your policies distribute benefits, risks, and opportunities?</li><li>Every group received the same residents, events, and chance results. What differences can therefore be explained by systems and choices?</li><li>How does protecting the least advantaged change your judgment of a “successful” system?</li></ol></section><div className="export"><button onClick={workbook}>Download teacher workbook</button><button onClick={()=>makePdf().save(`Behind_the_Veil_group_${seed}.pdf`)}>Download group PDF</button><button onClick={zip}>Download PDF ZIP</button></div><p className="disclaimer">Educational abstraction informed by evidence—not a prediction of any person's health.</p></main>
}

export default function App(){
 const [mode,setMode]=useState(null),[phase,setPhase]=useState('policy'),[selections,setSelections]=useState(initialSelections),[population,setPopulation]=useState(()=>createPopulation(residents)),[round,setRound]=useState(0);const [seed]=useState(()=>randomCode());
 useEffect(()=>{const saved=localStorage.getItem('btv-session');if(saved&&mode){try{const s=JSON.parse(saved);setSelections(s.selections);setPopulation(s.population);setPhase(s.phase);setRound(s.round)}catch{}}},[mode]);
 useEffect(()=>{if(mode)localStorage.setItem('btv-session',JSON.stringify({selections,population,phase,round,seed}))},[mode,selections,population,phase,round,seed]);
 const assignments=useMemo(()=>['A','B','C','D','E'],[]);
 if(!mode)return <Welcome onStart={m=>setMode(m)}/>;
 if(phase==='policy')return <PolicyLab selections={selections} setSelections={setSelections} practice={mode==='practice'} onContinue={()=>setPhase('residents')}/>;
 if(phase==='residents')return <Residents population={population} assignments={assignments} onContinue={()=>setPhase('trial')}/>;
 if(phase==='trial'&&round<trials.length)return <Trial trial={trials[round]} population={population} selections={selections} seed={seed} onComplete={p=>{setPopulation(p);setRound(round+1);if(round+1>=trials.length)setPhase('results')}}/>;
 return <Results population={population} selections={selections} seed={seed} onRestart={()=>{localStorage.removeItem('btv-session');location.reload()}}/>;
}
